### ISSUE TITLE
CMake Errors with new commit

### ISSUE THREAD

**Issue by xeTaiz** [inviwo/inviwo-old#14]
Hello,
after pulling the new update of inviwo I ran into CMake Errors:

```
CMake Warning at CMakeLists.txt:90 (find_package):
  By not providing "FindPythonLibsNew.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "PythonLibsNew", but CMake did not find one.

  Could not find a package configuration file provided by "PythonLibsNew"
  (requested version 3) with any of the following names:

    PythonLibsNewConfig.cmake
    pythonlibsnew-config.cmake

  Add the installation prefix of "PythonLibsNew" to CMAKE_PREFIX_PATH or set
  "PythonLibsNew_DIR" to a directory containing one of the above files.  If
  "PythonLibsNew" provides a separate development package or SDK, be sure it
  has been installed.


CMake Error at cmake/pybind11.cmake:33 (add_subdirectory):
  The source directory

    C:/Users/domin/Dev/Repos/inviwo/ext/pybind11

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  cmake/globalconfig.cmake:219 (include)
  CMakeLists.txt:93 (include)


CMake Error at cmake/pybind11.cmake:44 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".
Call Stack (most recent call first):
  modules/python3/CMakeLists.txt:124 (ivw_add_py_wrapper)
```

I have cloned the repo only as well to see whether it's related to my code and the same error occurs.
I attached the log files. As I have basically no idea of the python stuff, I don't really have an idea what the problem here is.

Greetings,
Dominik

[CMakeError.log.txt](https://github.com/inviwo/inviwo/files/1196534/CMakeError.log.txt)
[CMakeOutput.log.txt](https://github.com/inviwo/inviwo/files/1196533/CMakeOutput.log.txt)

**Comment by petersteneteg** [comment]
Hi

My initial guess would be that you have not added the submodules that we now use. Not sure when we started using submodules for various external but now we use a few of then. Make keeping then up to date much easier. To update them simply run:
```git submodule update --init```
after the clone. And let us know how it goes.

**Comment by xeTaiz** [comment]
Updating the ext/ modules seemed to fix my CMake issue, however the new python stuff that was added there gives me a lot of compile errors (see attachment). 


![image](https://user-images.githubusercontent.com/5837812/28919633-a1880b34-784e-11e7-946d-10a2805dd65e.png)

![image](https://user-images.githubusercontent.com/5837812/28919617-84756438-784e-11e7-9aa1-b8461569d11c.png)

**Comment by petersteneteg** [comment]
@r-englund: have you seen this before?

@xeTaiz: Im not sure what the issues is here. As a temporary workaround you can disable running and building the unit test in CMake.

**Comment by r-englund** [comment]
Hi, 
Could you check if the target inviwopy has been built? To make sure that it has been built you can right click the project in the solution explorer and select build.  If it has been built it will say it is up-to-date, if it isn't it may very well be the reason it fails.

**Comment by xeTaiz** [comment]
@petersteneteg  builds like a charm without unit tests, thank you very much

@r-englund  inviwopy has built successfully

**Comment by r-englund** [comment]
Does the python integration in inviwo work, try to load the three example workspaces. You can also try by opening the python editor and run the example script.

**Comment by petersteneteg** [comment]
The iterator issue above should be fixed in the latest commit.
