### ISSUE TITLE
New commits create instability 

### ISSUE THREAD

**Issue by stephane-lb** [inviwo/inviwo-old#15]
Hey,

So just did a git pull, clean everything and recompile it. 
So compilation is fine, however execution is a little bit buggy.
1- None of the example can be loaded ( Segfault )
2- OpenCL is not recognised anymore ( back again ), even by selecting Nvidia GT750M.
3- There are lot of : 
```
Warning: QObject::connect: signal not found in inviwo::PropertyWidgetQt ((null):0, (null))
```

I am going back to the previous version.

Best Regards,

stephane-lb

**Comment by petersteneteg** [comment]
Hi

I've tried to reproduce this problem, but have been unsuccessful. Could you share any more specific details?

**Comment by r-englund** [comment]
1. What QT version are you using? 
2. I have also had the OpenCL issue, what I did was to hard code which device to use in inviwoopencl.cpp to use.  In getBestGPUDeviceOnSystem function, I've changed the if statement to be 
```c++
auto devName = devices[j].getInfo<CL_DEVICE_NAME>();
if ( devName == "GeForce GTX 1060")
//if (deviceType != CL_DEVICE_TYPE_GPU || (otherDeviceType == CL_DEVICE_TYPE_GPU && maxComputeUnits < tmpMaxComputeUnits)) 
```
3. Attach your log output to the issue. To get the log start inviwo-cli with either -c (for a console logger) or -l filename (there is a bug with the filename for the file logger, easiest is to use a full path to a file, eg. inviwo-cli.exe -l C:/path/to/log.html

**Comment by stephane-lb** [comment]
Hi Rickard,

1 - Qt 5.9.1 
2 - Ok that's a solution. Are you using something like QSettings to encode the force ?
3 - sure ! See attached shared file : https://drive.google.com/open?id=0B4OKayijuI7xT3lkMXdsblRiQW8

Have a good week-end,

stephane-lb

**Comment by petersteneteg** [comment]
Hi,
I saw from the log that you are compiling using make, we do most our testing on OSX using XCode. This should in principle not make any difference, but... Have you tried compiling using XCode?

Could you compile in debug, and provide some stack traces from the crashes?

**Comment by stephane-lb** [comment]
Oh, sorry I think there is a misunderstanding there was no crash, simply lot of Warning for QtWidget which are not connecting.

**Comment by stephane-lb** [comment]
( Python3 was the one which creates instability )
